#!/bin/sh
commit_message=$(cat "$1")
pattern="^(feat|fix|chore|docs|style|refactor|test|perf|ci)(\([a-z0-9_-]+\))?: .+"

if ! echo "$commit_message" | grep -Eq "$pattern"; then
  echo "Error: Commit message does not follow Conventional Commits."
  exit 1
fi
